name: test-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        env:
          HZ_LICENSEKEY: "${HAZELCAST_LICENSE_KEY}"
        run: docker-compose up -d
      - name: Test
        env:
          HZ_LICENSEKEY: "${HAZELCAST_LICENSE_KEY}"
        run: |
          docker run --name hzkerberos_test \
              -e HZ_LICENSEKEY="${HZ_LICENSEKEY}" \
              --network=hazelcast-python-client-kerberos_hz \
              -v `pwd`:/home/hz/app
              -v hazelcast-python-client-kerberos_common:/common \
              hazelcast-python-client-kerberos_app:latest test
